server {
    listen 80;
    server_name localhost;

    index index.html;

    root /usr/src/static;

      location /home {
        proxy_pass http://localhost:3000/home;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /messages {
        proxy_pass http://localhost:3000/messages;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /hello_world {
        proxy_pass http://localhost:3000/hello_world;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /deploy {
        proxy_pass http://localhost:3000/deploy;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /how-backend-works {
        proxy_pass http://localhost:3000/how-backend-works;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /info {
        proxy_pass http://localhost:3000/info;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /resources {
        proxy_pass http://localhost:3000/resources;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }


    location /start {
        proxy_pass http://localhost:3000/start;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /submit {
        proxy_pass http://localhost:3000/submit;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    
}
